In [1]:
import xarray as xr

In [4]:
df = xr.open_dataset(r"C:\Users\Ankit\Datasets_Forest_fire\compressed_cleaned_era5_2015_2016.nc")

In [5]:
df.data_vars

Data variables:
    t2m      (valid_time, latitude, longitude) float32 16MB ...
    d2m      (valid_time, latitude, longitude) float32 16MB ...
    u10      (valid_time, latitude, longitude) float32 16MB ...
    v10      (valid_time, latitude, longitude) float32 16MB ...
    tp       (valid_time, latitude, longitude) float32 16MB ...

In [7]:
import numpy as np 
np.unique(df['tp'].values.max())

array([56.596756], dtype=float32)

In [8]:
np.unique(df['tp'].values.min())

array([0.], dtype=float32)

In [13]:
np.unique(df['u10'].values.min())

array([-9.634323], dtype=float32)

In [14]:
np.unique(df['v10'].values.min())

array([-8.777985], dtype=float32)

In [15]:
np.unique(df['d2m'].values.min())

array([-58.624878], dtype=float32)

In [16]:
np.unique(df['t2m'].values.min())

array([-40.594254], dtype=float32)

In [21]:
import numpy as np

for var in df.data_vars:
    data = df[var].values  # get numpy array
    print(f"{var}: min={np.nanmin(data)}, max={np.nanmax(data)}")

t2m: min=-40.59425354003906, max=44.880035400390625
d2m: min=-58.6248779296875, max=31.104156494140625
u10: min=-9.634323120117188, max=9.16412353515625
v10: min=-8.777984619140625, max=9.072845458984375
tp: min=0.0, max=56.59675598144531
